# Config file for automatic testing at travis-ci.org
language: python

# Installs python 3.5 in travis. 2.7 installed for free. tox runs both
python:
    - 3.5

env:
    - TOX_ENV=py27
    - TOX_ENV=py35
script: tox -e $TOX_ENV
install: pip install tox
